version: '3'

services:
  app:
    build: .
    image: 'docker-wildfly:latest'
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/localdev
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    # container_name: docker-postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=localdev
    ports:
      - 5432:5432